/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {};

declare module "@vue/runtime-core" {
  export interface GlobalComponents {
    Avatar: typeof import("./src/components/Upload/avatar.vue")["default"];
    Bar: typeof import("./src/components/Chart/bar.vue")["default"];
    ElBadge: typeof import("element-plus/es")["ElBadge"];
    ElBreadcrumb: typeof import("element-plus/es")["ElBreadcrumb"];
    ElBreadcrumbItem: typeof import("element-plus/es")["ElBreadcrumbItem"];
    ElButton: typeof import("element-plus/es")["ElButton"];
    ElCarousel: typeof import("element-plus/es")["ElCarousel"];
    ElCarouselItem: typeof import("element-plus/es")["ElCarouselItem"];
    ElCheckbox: typeof import("element-plus/es")["ElCheckbox"];
    ElCheckboxGroup: typeof import("element-plus/es")["ElCheckboxGroup"];
    ElCol: typeof import("element-plus/es")["ElCol"];
    ElDatePicker: typeof import("element-plus/es")["ElDatePicker"];
    ElDialog: typeof import("element-plus/es")["ElDialog"];
    ElDivider: typeof import("element-plus/es")["ElDivider"];
    ElDrawer: typeof import("element-plus/es")["ElDrawer"];
    ElDropdown: typeof import("element-plus/es")["ElDropdown"];
    ElDropdownItem: typeof import("element-plus/es")["ElDropdownItem"];
    ElDropdownMenu: typeof import("element-plus/es")["ElDropdownMenu"];
    ElEmpty: typeof import("element-plus/es")["ElEmpty"];
    ElForm: typeof import("element-plus/es")["ElForm"];
    ElFormItem: typeof import("element-plus/es")["ElFormItem"];
    ElIcon: typeof import("element-plus/es")["ElIcon"];
    ElImageViewer: typeof import("element-plus/es")["ElImageViewer"];
    ElInput: typeof import("element-plus/es")["ElInput"];
    ElLink: typeof import("element-plus/es")["ElLink"];
    ElMenu: typeof import("element-plus/es")["ElMenu"];
    ElMenuItem: typeof import("element-plus/es")["ElMenuItem"];
    ElOption: typeof import("element-plus/es")["ElOption"];
    ElPagination: typeof import("element-plus/es")["ElPagination"];
    ElPopover: typeof import("element-plus/es")["ElPopover"];
    ElResult: typeof import("element-plus/es")["ElResult"];
    ElRow: typeof import("element-plus/es")["ElRow"];
    ElScrollbar: typeof import("element-plus/es")["ElScrollbar"];
    ElSelect: typeof import("element-plus/es")["ElSelect"];
    ElSubMenu: typeof import("element-plus/es")["ElSubMenu"];
    ElSwitch: typeof import("element-plus/es")["ElSwitch"];
    ElTable: typeof import("element-plus/es")["ElTable"];
    ElTableColumn: typeof import("element-plus/es")["ElTableColumn"];
    ElTabPane: typeof import("element-plus/es")["ElTabPane"];
    ElTabs: typeof import("element-plus/es")["ElTabs"];
    ElTree: typeof import("element-plus/es")["ElTree"];
    ElUpload: typeof import("element-plus/es")["ElUpload"];
    File: typeof import("./src/components/Upload/file.vue")["default"];
    Img: typeof import("./src/components/Upload/img.vue")["default"];
    ImportDialog: typeof import("./src/components/Upload/importDialog.vue")["default"];
    Line: typeof import("./src/components/Chart/line.vue")["default"];
    Map: typeof import("./src/components/Chart/map.vue")["default"];
    Mix: typeof import("./src/components/Chart/mix.vue")["default"];
    MoreBar: typeof import("./src/components/Chart/more-bar.vue")["default"];
    MoreLine: typeof import("./src/components/Chart/more-line.vue")["default"];
    Pie: typeof import("./src/components/Chart/pie.vue")["default"];
    ProTable: typeof import("./src/components/ProTable/index.vue")["default"];
    RouterLink: typeof import("vue-router")["RouterLink"];
    RouterView: typeof import("vue-router")["RouterView"];
    SearchForm: typeof import("./src/components/SearchForm/index.vue")["default"];
    SvgIcon: typeof import("./src/components/SvgIcon/index.vue")["default"];
    VerifyCode: typeof import("./src/components/VerifyCode/index.vue")["default"];
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import("element-plus/es")["ElLoadingDirective"];
    vPopover: typeof import("element-plus/es")["ElPopoverDirective"];
  }
}
